import os
import browser_cookie3

HEADER = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.
"""

OUTPUT_DIR = "cookies"

def get_chrome_profiles():
    home = os.path.expanduser("~")
    possible_paths = [
        os.path.join(home, ".config", "google-chrome"),
        os.path.join(home, "snap", "google-chrome", "common", ".config", "google-chrome")
    ]
    
    user_data_dir = None
    for p in possible_paths:
        if os.path.exists(p):
            user_data_dir = p
            break
            
    if not user_data_dir:
        return []

    profiles = []
    for folder in os.listdir(user_data_dir):
        if folder == 'Default' or folder.startswith('Profile '):
            profile_path = os.path.join(user_data_dir, folder)
            paths_to_check = [
                os.path.join(profile_path, 'Network', 'Cookies'),
                os.path.join(profile_path, 'Cookies')
            ]
            for p in paths_to_check:
                if os.path.exists(p):
                    profiles.append({'name': folder, 'path': p})
                    break
    
    profiles.sort(key=lambda x: x['name'])
    return profiles

def write_cookies_to_file(cookies, filename):
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(HEADER + "\n")
        for c in cookies:
            domain = c.domain
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = c.path
            secure = 'TRUE' if c.secure else 'FALSE'
            expiry = str(int(c.expires)) if c.expires else '0'
            name = c.name
            value = c.value
            
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

def save_chrome_cookies(cookie_path, filename):
    try:
        cookies = browser_cookie3.chrome(domain_name='.youtube.com', cookie_file=cookie_path)
        write_cookies_to_file(cookies, filename)
        print(f"Success. Chrome cookies saved to {filename}")
    except Exception as e:
        print(f"Error extracting Chrome cookies: {e}")

def save_firefox_cookies(filename):
    try:
        cookies = browser_cookie3.firefox(domain_name='.youtube.com')
        write_cookies_to_file(cookies, filename)
        print(f"Success. Firefox cookies saved to {filename}")
    except Exception as e:
        print(f"Firefox cookies not found or database locked: {e}")

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    profiles = get_chrome_profiles()
    
    if profiles:
        print("--- Processing Chrome Profiles ---")
        for idx, p in enumerate(profiles, start=1):
            filename = os.path.join(OUTPUT_DIR, f"cookies_{idx}.txt")
            print(f"Extracting from [{p['name']}]...")
            save_chrome_cookies(p['path'], filename)
    else:
        print("Chrome data directory or profiles not found.")

    print("\n--- Processing Firefox ---")
    firefox_filename = os.path.join(OUTPUT_DIR, "cookies_fire.txt")
    save_firefox_cookies(firefox_filename)

if __name__ == "__main__":
    main()